### ISSUE TITLE
Right clicking heads replaces helmet in survival and messes up permissions

### ISSUE THREAD

**Issue by Em1tt** [IHasName/CustomHeads#32] opened 2021-08-23 18:29 UTC
## Issue Description

Our permissions plugin is LuckPerms, version is latest.
We're running your plugin on an SMP server, and one of the members had a full inventory, except for one slot, and was left-clicking through heads, so they'd fill the clear spot, and then he threw the heads on the ground, and repeated the process until he accidentally right clicked the head which instantly replaced his netherite helmet with the head he right clicked. He did /heads again, and then his permissions were all messed up where he couldn't access any categories. This permission issue was resolved when he rejoined the server.

## Possible solution
Add a config option to toggle right clicking a head instantly replacing it with your current head slot

## Infos
  - Plugin Version: 3.0.3
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2): Paper 1.17.1

**Comment by IHasName** [comment] 2021-08-26 17:52
Only right clicking the Head shouldn't replace the Head but I'll look into it and add the Option to disable this Feature.
Im not sure what caused the Permission Issue but did all Categories appear with the (Locked) Suffix or was he just not able to access them (unresponsive)?

**Comment by ArcticTaco** [comment] 2021-12-07 20:26
Hello, I was able to reproduce this issue. I do not believe the steps I did to reproduce this has to be this concise, but this is how I am doing it consistently. SHIFT-LEFT-CLICK one head. SHIFT-LEFT-CLICK a different head. SHIFT-RIGHT-CLICK another head. This will replace the helmet with the head you selected without giving back the helmet.

**Comment by IHasName** [comment] 2021-12-07 20:40
Well... yes... Shift + Right Click replaces the Helmet Slot without giving it back (currently)... It says that on the Paper thats in the Inventory

**Comment by ArcticTaco** [comment] 2021-12-07 20:56
Alright. So is this _feature_ going to be revamped in the near future? I like the idea of the OP that we could disable this in the config. Also, is it really a feature if half the time it returns the helmet and half the time it doesn't? Seems faulty...

**Comment by IHasName** [comment] 2021-12-07 21:02
No. By "Replace" I mean literally replace it in the Slot itself not returning it to the Inventory at all...
Seems more like a coincidence it returns half the time since I just set it via the Plugin

**Comment by ArcticTaco** [comment] 2021-12-07 21:09
Okay... either way if your intended result is to always replace without giving it back, or to give it back whilst replacing it, it seems to be a bug considering half and half is not planned. Coincidence is a weird word choice. Are you planning to fix this bug? I ask because I notice the plugin has not received an update in a while. (Jul 20, 2021)

**Comment by ArcticTaco** [comment] 2021-12-07 21:09
Also sorry if I come off badly, I do appreciate your work on this plugin and it has helped me and the server I run a lot.

**Comment by IHasName** [comment] 2021-12-07 21:25
It's fine... I've been working on the Updates pretty inconsistently. Thats mostly due to planned Features that take way to long to implement and other Bugs that occour
Updates will come out eventually but I can't give an ETA for anything really
Also if my English seems off sometimes... thats mostly due to not being my first Language xD

Also if you're curious [this](https://github.com/IHasName/CustomHeads/blob/master/src/main/java/de/likewhat/customheads/listener/InventoryListener.java#L539) is where i set the Helment Slot

**Comment by IHasName** [comment] 2023-10-13 21:13
I'll be closing this Issue since it should all be resolved with the upcoming Release
Though the Permission Issue was unrelated to this one but yeah

**Closed as completed by IHasName** 2023-10-13 21:13 UTC
